list = [10,40,30,20,50]
print("the first element is ",list[0])
print("the fourt element is ",list[3])
print("print the element bteween the 0,2 ",list[0:3])
list.append(20)
print("the append element is ",list )
print("print the index of 20 ",list.index(20))
list .sort()
print("list after sorting ",list )
print("the popped element is ",list.pop())
print("list after sortn",list)
list .insert(2,50)
print("the list after insert ",list )
print("the number of 20 occure",list.count(20))
list.remove(10)
print("list after remove 10 ", list )
list.reverse()
print("the after reverse ",list )

