import numpy as np
a = np.array(42)
b = np.array([1, 2, 3, 4, 5,6])
c = np.array([[1, 2, 3,4,5], [6,7,8,9,10]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[10, 20, 30], [40, 50, 60]]])
print("Dimension of array a",a.ndim)
print("Dimension of array d",d.ndim)
print("No of elements in each dimension of array c",c.shape)
print("Different types of arrays")
print(a)
print(b)
print(c)
print(d)
e=np.arange(2, 10)
print(e)
print("array after addition",b[2] + b[3])
print("Array after slicing")
print(d[1, 1, 2])
print(c[1, 1:4])
print("Array after copying")
x = b.copy()
y = b.view()
print(x.base)
print(y.base)
print("b array after reshaping")
newarr = b.reshape(2, 3)
print(newarr)
m = np.array([[1, 2], [3, 4]])
n = np.array([[5, 6], [7, 8]])
o = np.concatenate((m, n), axis=1)
print("Array after concatinatoin",o)
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
new= np.array_split(arr, 3)
print("array after splitting",new)
print("Searching even indexed values from array b")
x = np.where(b%2 == 0)
print(x)